# This is a basic workflow to help you get started with Actions

name: pics

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:hkc452/pics.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:hkc/pics.git"
    # 屏蔽发布 pages
    # - name: Build Gitee Pages
    #   uses: yanglbme/gitee-pages-action@master
    #   with:
    #       # 注意替换为你的 Gitee 用户名
    #       gitee-username: hkc
    #       # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
    #       gitee-password: ${{ secrets.GITEE_PASSWORD }}
    #       # 注意替换为你的 Gitee 仓库
    #       gitee-repo: hkc/pics
